### PR TITLE
[feature] Expect saga

### PR DESCRIPTION
**Pull request by HenriBeck**
This builds on top of #41 and implements the interface proposed in #37 

There a few TODOs left to discuss but otherwise, it's done.

### CODE REVIEW

**Comment by HenriBeck** [comment]
Screenshot 2019-03-30 at 09 46 10

I played around error stack traces and got them to show the actual code where an assertion fails in the source code.

**Comment by HenriBeck** [comment]
@tp Please review

**Comment by tp** [comment]
@HenriBeck Will do tomorrow morning. Just saw the stack trace improvement. Getting the "call site" might be awfully handy :)

**Comment by tp** [comment]
@HenriBeck This is really nice, thanks a lot. I'll merge and publish now so you can use it in app 🎉

**Comment by HenriBeck** [comment]
@tp Nice, I will play around with it this week and see if there are any bugs left.

**Pull request merged**
